sudo: required

language: bash
services: docker

before_install:
  - sudo apt update -y
  - sudo apt install --only-upgrade docker-ce -y
script:
  - docker --version
  - docker-compose --version
  - make build

after_success:
  - test $TRAVIS_BRANCH = "master" && make push
